---
#handlers file for app
#- name: reload systemd
#  command: systemctl daemon-reload
#- name: reload puma
#  command: systemctl restart puma
- name: reload puma
  systemd: name=puma state=restarted
