- name: Configure App
  hosts: app
  become: true
  vars: 
    db_host: 10.128.0.26
  tasks:      
    - name: Add unit file for Puma
      copy:
        src: files/puma.service
        dest: /etc/systemd/system/puma.service
      notify: reload systemd
    
    - name: Add config for DB connection
      template:
        src: templates/db_config.j2
        dest: /home/ubuntu/db_config
    
    - name: enable puma
      systemd: name=puma enabled=yes
       
  handlers: #<-- добавим блок и задачу
  - name: reload systemd
    command: systemctl daemon-reload
  - name: reload puma
    command: systemctl restart puma
